/* KPOS Inventory Pro - suppliers, purchase cost history, stocktake, adjustments, Excel */
(function(){
  const desktopMQ=window.matchMedia('(min-width:980px)');
  const isDesktop=()=>desktopMQ.matches;
  const baseRender=window.render;
  const baseModalView=window.modalView;
  const baseFinishStockReceipt=window.finishStockReceipt;

  function ensure(save=false){
    let changed=false;
    if(!Array.isArray(db.suppliers)){db.suppliers=[];changed=true}
    if(!Array.isArray(db.costHistory)){db.costHistory=[];changed=true}
    if(!Array.isArray(db.inventoryCounts)){db.inventoryCounts=[];changed=true}
    if(!Array.isArray(db.adjustmentReceipts)){db.adjustmentReceipts=[];changed=true}
    (db.products||[]).forEach(p=>{if(!Array.isArray(p.costHistory)){p.costHistory=[];changed=true}});
    if(changed&&save)saveDB();
  }
  ensure(true);

  const docCode=(prefix,collection=[])=>window.KPOS_DOC_CODE?window.KPOS_DOC_CODE(prefix,collection,new Date()):code(prefix,collection);
  const supplier=id=>(db.suppliers||[]).find(x=>String(x.id)===String(id));
  const adjustment=id=>(db.adjustmentReceipts||[]).find(x=>String(x.id)===String(id));
  const countDoc=id=>(db.inventoryCounts||[]).find(x=>String(x.id)===String(id));
  const normalProduct=p=>p&&!p.imeiEnabled;

  function injectQuickLinks(){
    if(!['more','stock','inventory','settings','dashboard'].includes(state.screen))return;
    const content=document.querySelector('.content');if(!content)return;
    if((state.screen==='more'||state.screen==='stock'||state.screen==='inventory')&&!document.querySelector('#inventory-pro-links')){
      const box=document.createElement('div');box.id='inventory-pro-links';box.className='card inventory-pro-links';
      box.innerHTML=`<div class="row-between"><div><b>Kho & mua hàng nâng cao</b><div class="small muted">Nhà cung cấp • giá nhập • kiểm kho • điều chỉnh • Excel</div></div></div><div class="inventory-pro-actions"><button class="btn ghost small" onclick="goInventoryPro('suppliers')">🏭 Nhà cung cấp</button><button class="btn ghost small" onclick="openStocktake()">✅ Kiểm kho</button><button class="btn ghost small" onclick="goInventoryPro('adjustments')">⇅ Điều chỉnh kho</button><button class="btn ghost small" onclick="exportProductsExcel()">⬇ Excel</button><button class="btn ghost small" onclick="importProductsExcel()">⬆ Nhập Excel</button></div>`;
      content.prepend(box);
    }
    if(state.screen==='dashboard'&&!document.querySelector('#inventory-low-stock')){
      const low=(db.products||[]).filter(p=>(Number(p.stock)||0)<=(Number(p.minStock)||0)).sort((a,b)=>(a.stock-a.minStock)-(b.stock-b.minStock));
      if(low.length){const box=document.createElement('div');box.id='inventory-low-stock';box.className='card inventory-low-stock';box.innerHTML=`<div class="row-between"><div><b>⚠️ Hàng sắp hết</b><div class="small muted">${low.length} sản phẩm bằng hoặc dưới tồn tối thiểu</div></div><button class="btn ghost small" onclick="go('products')">Xem hàng hóa</button></div><div class="inventory-low-list">${low.slice(0,8).map(p=>`<button onclick="openProductDetail(${p.id})"><span><b>${esc(p.name)}</b><small>${esc(p.sku||'')} • tối thiểu ${p.minStock||0}</small></span><b class="danger-text">Tồn ${p.stock||0}</b></button>`).join('')}</div>`;content.appendChild(box)}
    }
    if(state.modal?.type==='productDetail'&&!document.querySelector('#inventory-cost-history')){
      const p=state.modal.p||product(state.modal.productId);if(!p)return;const rows=(db.costHistory||[]).filter(x=>x.productId===p.id).slice(0,10);const sheet=document.querySelector('.sheet');if(!sheet)return;const box=document.createElement('div');box.id='inventory-cost-history';box.className='card inventory-cost-history';box.innerHTML=`<div class="row-between"><div><b>Lịch sử giá nhập / giá vốn</b><div class="small muted">Giá vốn hiện tại: ${money(p.cost||0)}</div></div></div><div class="inventory-cost-list">${rows.map(x=>`<div><span><b>${fmtDateTime(x.date)}</b><small>${esc(supplier(x.supplierId)?.name||x.supplierName||'Không NCC')} • ${esc(x.receiptCode||'')}</small></span><span class="right"><b>${money(x.buyPrice)}</b><small>Giá vốn ${money(x.oldCost)} → ${money(x.newCost)}</small></span></div>`).join('')||'<div class="empty">Chưa có lịch sử giá nhập.</div>'}</div>`;sheet.appendChild(box)}
  }

  window.goInventoryPro=screen=>{state.screen=screen;state.modal=null;render();scrollTo(0,0)};

  function suppliersView(){ensure();const q=String(state.supplierSearch||'').toLowerCase(),list=(db.suppliers||[]).filter(s=>[s.code,s.name,s.phone,s.email,s.address,s.taxCode].some(v=>String(v||'').toLowerCase().includes(q)));return `${topbar('Nhà cung cấp','Thông tin mua hàng • lịch sử nhập')}<div class="content inventory-pro-page"><div class="inventory-pro-toolbar"><div class="searchrow"><input id="supplierSearch" placeholder="Tên, mã, SĐT, MST..." value="${esc(state.supplierSearch||'')}" oninput="state.supplierSearch=this.value;render()"></div><button class="btn primary" onclick="openSupplierForm()">＋ Nhà cung cấp</button></div><div class="inventory-pro-table"><div class="inventory-pro-tr head"><div>Nhà cung cấp</div><div>Liên hệ</div><div>Lịch sử mua</div><div class="right">Thao tác</div></div>${list.map(s=>{const receipts=(db.stockReceipts||[]).filter(r=>String(r.supplierId)===String(s.id)&&r.status!=='Đã hủy'),value=receipts.reduce((a,r)=>a+(r.items||[]).reduce((x,it)=>x+(Number(it.qty)||0)*(Number(it.buyPrice)||Number(product(it.productId)?.cost)||0),0),0);return `<div class="inventory-pro-tr"><div><b>${esc(s.name)}</b><small>${esc(s.code||'')} ${s.taxCode?`• MST ${esc(s.taxCode)}`:''}</small></div><div><b>${esc(s.phone||'—')}</b><small>${esc(s.email||s.address||'')}</small></div><div><b>${receipts.length} phiếu nhập</b><small>${money(value)}</small></div><div class="right"><button class="btn ghost small" onclick="openSupplierDetail('${s.id}')">Xem</button><button class="btn ghost small" onclick="openSupplierForm('${s.id}')">Sửa</button></div></div>`}).join('')||'<div class="empty">Chưa có nhà cung cấp.</div>'}</div></div>${nav()}`}

  window.openSupplierForm=id=>{ensure();const s=id?supplier(id):{id:'',code:'',name:'',phone:'',email:'',address:'',taxCode:'',note:'',active:true};state.modal={type:'supplierForm',s:clone(s),editing:!!id};render()};
  window.saveSupplier=()=>{const m=state.modal,s=m.s;s.code=$('#sup_code')?.value.trim()||s.code||`NCC${String(Date.now()).slice(-5)}`;s.name=$('#sup_name')?.value.trim()||'';s.phone=$('#sup_phone')?.value.trim()||'';s.email=$('#sup_email')?.value.trim()||'';s.address=$('#sup_address')?.value.trim()||'';s.taxCode=$('#sup_tax')?.value.trim()||'';s.note=$('#sup_note')?.value.trim()||'';s.active=$('#sup_active')?.checked!==false;if(!s.name)return toast('Nhập tên nhà cung cấp');if((db.suppliers||[]).some(x=>String(x.id)!==String(s.id)&&String(x.code||'').toLowerCase()===String(s.code||'').toLowerCase()))return toast('Mã nhà cung cấp đã tồn tại');if(m.editing){db.suppliers[db.suppliers.findIndex(x=>String(x.id)===String(s.id))]=s}else{s.id=Date.now();db.suppliers.unshift(s)}saveDB();state.modal=null;state.screen='suppliers';render();toast('Đã lưu nhà cung cấp')};
  window.openSupplierDetail=id=>{const s=supplier(id);if(!s)return;state.modal={type:'supplierDetail',s};render()};
  window.deleteSupplier=id=>{const s=supplier(id);if(!s)return;const used=(db.stockReceipts||[]).some(r=>String(r.supplierId)===String(id));if(used)return toast('Nhà cung cấp đã có phiếu nhập nên không thể xóa. Có thể tắt trạng thái hoạt động.');if(!confirm(`Xóa nhà cung cấp "${s.name}"?`))return;db.suppliers=db.suppliers.filter(x=>String(x.id)!==String(id));saveDB();state.modal=null;state.screen='suppliers';render()};

  function stocktakeView(){ensure();if(!state.stocktakeDraft)window.startStocktake();const d=state.stocktakeDraft,q=String(state.stocktakeSearch||'').toLowerCase(),items=d.items.filter(it=>{const p=product(it.productId);return [p?.name,p?.sku,p?.barcode].some(v=>String(v||'').toLowerCase().includes(q))}),diffs=d.items.filter(x=>Number(x.actualQty)!==Number(x.systemQty));return `${topbar('Kiểm kho thực tế','Đếm hàng • so sánh tồn • tạo phiếu điều chỉnh')}<div class="content inventory-pro-page"><div class="inventory-pro-toolbar"><div class="searchrow"><input placeholder="Tìm sản phẩm..." value="${esc(state.stocktakeSearch||'')}" oninput="state.stocktakeSearch=this.value;render()"></div><div class="inventory-pro-actions"><button class="btn ghost" onclick="resetStocktakeActual()">Đặt = tồn hệ thống</button><button class="btn primary" onclick="completeStocktake()">HOÀN TẤT KIỂM KHO</button></div></div><div class="notice">Chênh lệch hiện tại: <b>${diffs.length}</b> sản phẩm. Với hàng quản lý IMEI/Serial, hệ thống không tự tăng/giảm tồn nếu thiếu danh tính IMEI.</div><div class="inventory-pro-table stocktake"><div class="inventory-pro-tr head"><div>Sản phẩm</div><div class="right">Tồn hệ thống</div><div class="right">Thực tế</div><div class="right">Chênh lệch</div></div>${items.map(it=>{const p=product(it.productId),diff=Number(it.actualQty)-Number(it.systemQty);return `<div class="inventory-pro-tr"><div><b>${esc(p?.name||'')}</b><small>${esc(p?.sku||'')} ${p?.imeiEnabled?'• IMEI/Serial':''}</small></div><div class="right"><b>${it.systemQty}</b></div><div class="right"><input type="number" min="0" value="${it.actualQty}" onchange="setStocktakeActual(${it.productId},this.value)"></div><div class="right"><b class="${diff<0?'danger-text':diff>0?'success-text':''}">${diff>0?'+':''}${diff}</b></div></div>`}).join('')}</div><div class="field"><label>Ghi chú kiểm kho</label><textarea id="stocktake_note" rows="2" oninput="state.stocktakeDraft.note=this.value">${esc(d.note||'')}</textarea></div></div>${nav()}`}
  window.startStocktake=()=>{state.stocktakeDraft={date:new Date().toISOString(),note:'',items:(db.products||[]).map(p=>({productId:p.id,systemQty:Number(p.stock)||0,actualQty:Number(p.stock)||0}))};state.screen='stocktake';state.modal=null;render()};
  window.openStocktake=window.startStocktake;
  window.setStocktakeActual=(id,v)=>{const it=state.stocktakeDraft?.items.find(x=>x.productId===id);if(it)it.actualQty=Math.max(0,Number(v)||0)};
  window.resetStocktakeActual=()=>{(state.stocktakeDraft?.items||[]).forEach(it=>it.actualQty=it.systemQty);render()};
  window.completeStocktake=()=>{ensure();const d=state.stocktakeDraft;if(!d)return;const diffs=d.items.filter(x=>Number(x.actualQty)!==Number(x.systemQty));const blocked=diffs.filter(x=>product(x.productId)?.imeiEnabled);if(blocked.length)return toast(`Có ${blocked.length} sản phẩm IMEI bị lệch. Hãy xử lý IMEI cụ thể trước khi cân bằng tồn.`);if(!diffs.length){const doc={id:Date.now(),code:docCode('KK',db.inventoryCounts),date:new Date().toISOString(),status:'Hoàn thành',note:d.note||'',items:clone(d.items),adjustmentId:null};db.inventoryCounts.unshift(doc);saveDB();state.stocktakeDraft=null;toast('Kiểm kho hoàn tất, không có chênh lệch');state.screen='inventory';render();return}if(!confirm(`Có ${diffs.length} sản phẩm chênh lệch. Tạo phiếu điều chỉnh tồn theo số đếm thực tế?`))return;const adj={id:Date.now(),code:docCode('DC',db.adjustmentReceipts),date:new Date().toISOString(),status:'Hoàn thành',reason:'Điều chỉnh từ kiểm kho',note:d.note||'',items:[]};diffs.forEach(it=>{const p=product(it.productId),before=Number(p.stock)||0,after=Math.max(0,Number(it.actualQty)||0),delta=after-before;p.stock=after;adj.items.push({productId:p.id,before,after,delta});addMovement(p.id,delta,'STOCKTAKE',adj.code,'Điều chỉnh từ kiểm kho')});db.adjustmentReceipts.unshift(adj);const doc={id:Date.now()+1,code:docCode('KK',db.inventoryCounts),date:new Date().toISOString(),status:'Hoàn thành',note:d.note||'',items:clone(d.items),adjustmentId:adj.id};db.inventoryCounts.unshift(doc);addActivity(`${doc.code} • ${diffs.length} chênh lệch • ${adj.code}`);saveDB();state.stocktakeDraft=null;state.screen='adjustments';render();toast('Đã hoàn tất kiểm kho và tạo phiếu điều chỉnh')};

  function adjustmentsView(){ensure();const list=db.adjustmentReceipts||[];return `${topbar('Điều chỉnh kho','Phiếu điều chỉnh • kiểm kho • tồn thực tế')}<div class="content inventory-pro-page"><div class="inventory-pro-toolbar"><div><b>${list.length} phiếu điều chỉnh</b><div class="small muted">Hàng IMEI/Serial phải điều chỉnh qua luồng có IMEI cụ thể.</div></div><button class="btn primary" onclick="openAdjustmentForm()">＋ Phiếu điều chỉnh</button></div><div class="inventory-pro-table"><div class="inventory-pro-tr head"><div>Chứng từ</div><div>Lý do</div><div>Số dòng</div><div class="right">Trạng thái</div></div>${list.map(a=>`<button class="inventory-pro-tr" onclick="openAdjustmentDetail(${a.id})"><div><b>${esc(a.code)}</b><small>${fmtDateTime(a.date)}</small></div><div><b>${esc(a.reason||'Điều chỉnh kho')}</b><small>${esc(a.note||'')}</small></div><div><b>${(a.items||[]).length} sản phẩm</b></div><div class="right"><span class="badge ${a.status==='Đã hủy'?'red':'green'}">${esc(a.status||'Hoàn thành')}</span></div></button>`).join('')||'<div class="empty">Chưa có phiếu điều chỉnh.</div>'}</div></div>${nav()}`}
  window.openAdjustmentForm=()=>{const products=(db.products||[]).filter(normalProduct);state.modal={type:'adjustmentForm',draft:{reason:'Kiểm kê / điều chỉnh thực tế',note:'',items:[]},available:products};render()};
  window.addAdjustmentLine=()=>{const id=Number($('#adj_product')?.value),delta=Number($('#adj_delta')?.value)||0,p=product(id),m=state.modal;if(!p||!delta)return toast('Chọn sản phẩm và nhập số lượng chênh lệch khác 0');if(p.imeiEnabled)return toast('Hàng IMEI/Serial phải điều chỉnh bằng IMEI cụ thể');const found=m.draft.items.find(x=>x.productId===id);if(found)found.delta+=delta;else m.draft.items.push({productId:id,delta});render()};
  window.removeAdjustmentLine=idx=>{state.modal.draft.items.splice(idx,1);render()};
  window.saveAdjustment=()=>{const m=state.modal,d=m.draft;d.reason=$('#adj_reason')?.value.trim()||d.reason;d.note=$('#adj_note')?.value.trim()||'';if(!d.items.length)return toast('Chưa có sản phẩm điều chỉnh');for(const it of d.items){const p=product(it.productId),after=(Number(p.stock)||0)+(Number(it.delta)||0);if(after<0)return toast(`${p.name}: tồn sau điều chỉnh không thể âm`)}const a={id:Date.now(),code:docCode('DC',db.adjustmentReceipts),date:new Date().toISOString(),status:'Hoàn thành',reason:d.reason,note:d.note,items:[]};d.items.forEach(it=>{const p=product(it.productId),before=Number(p.stock)||0,after=before+Number(it.delta);p.stock=after;a.items.push({productId:p.id,before,after,delta:Number(it.delta)});addMovement(p.id,Number(it.delta),'ADJUST',a.code,d.reason)});db.adjustmentReceipts.unshift(a);addActivity(`${a.code} • ${a.reason}`);saveDB();state.modal={type:'adjustmentDetail',a};render();toast('Đã tạo phiếu điều chỉnh')};
  window.openAdjustmentDetail=id=>{const a=adjustment(id);if(!a)return;state.modal={type:'adjustmentDetail',a};render()};
  window.cancelAdjustment=id=>{const a=adjustment(id);if(!a||a.status==='Đã hủy')return;for(const it of a.items||[]){const p=product(it.productId);if(!p)return;if((Number(p.stock)||0)-(Number(it.delta)||0)<0)return toast(`${p.name}: không thể đảo phiếu vì tồn sẽ âm`)}if(!confirm(`Hủy ${a.code} và đảo toàn bộ biến động tồn?`))return;(a.items||[]).forEach(it=>{const p=product(it.productId);p.stock=(Number(p.stock)||0)-(Number(it.delta)||0);addMovement(p.id,-Number(it.delta),'ADJUST_CANCEL',a.code,'Hủy phiếu điều chỉnh')});a.status='Đã hủy';a.cancelledAt=new Date().toISOString();saveDB();state.modal={type:'adjustmentDetail',a};render();toast('Đã hủy phiếu điều chỉnh')};

  function supplierFormModal(m){const s=m.s;return sheet(m.editing?'Sửa nhà cung cấp':'Thêm nhà cung cấp',`<div class="form-row"><div class="field"><label>Mã NCC</label><input id="sup_code" value="${esc(s.code||'')}"></div><div class="field"><label>Tên nhà cung cấp *</label><input id="sup_name" value="${esc(s.name||'')}"></div></div><div class="form-row"><div class="field"><label>SĐT</label><input id="sup_phone" value="${esc(s.phone||'')}"></div><div class="field"><label>Email</label><input id="sup_email" value="${esc(s.email||'')}"></div></div><div class="field"><label>Địa chỉ</label><input id="sup_address" value="${esc(s.address||'')}"></div><div class="field"><label>Mã số thuế</label><input id="sup_tax" value="${esc(s.taxCode||'')}"></div><div class="field"><label>Ghi chú</label><textarea id="sup_note" rows="3">${esc(s.note||'')}</textarea></div><label class="checkrow"><input id="sup_active" type="checkbox" ${s.active!==false?'checked':''}> Đang hoạt động</label><div class="split-buttons" style="margin-top:12px"><button class="btn ghost" onclick="closeModal()">Đóng</button><button class="btn primary" onclick="saveSupplier()">LƯU NHÀ CUNG CẤP</button></div>`)}
  function supplierDetailModal(m){const s=m.s,rs=(db.stockReceipts||[]).filter(r=>String(r.supplierId)===String(s.id)).slice(0,20),hist=(db.costHistory||[]).filter(x=>String(x.supplierId)===String(s.id)).slice(0,20);return sheet(s.name,`<div class="inventory-supplier-kpis"><div><span>Phiếu nhập</span><b>${rs.filter(r=>r.status!=='Đã hủy').length}</b></div><div><span>Lần nhập giá</span><b>${hist.length}</b></div><div><span>Trạng thái</span><b>${s.active===false?'Ngừng':'Hoạt động'}</b></div></div><div class="card"><div><b>${esc(s.phone||'—')}</b> • ${esc(s.email||'')}</div><div class="small muted">${esc(s.address||'')}</div>${s.taxCode?`<div class="small muted">MST: ${esc(s.taxCode)}</div>`:''}</div><div class="section-title">Phiếu nhập gần đây</div><div class="inventory-cost-list">${rs.map(r=>`<button onclick="openStockReceiptDetail(${r.id})"><span><b>${esc(r.code)}</b><small>${fmtDateTime(r.date)} • ${esc(r.status||'')}</small></span><span class="right"><b>${(r.items||[]).reduce((a,b)=>a+(Number(b.qty)||0),0)} SP</b></span></button>`).join('')||'<div class="empty">Chưa có phiếu nhập.</div>'}</div><div class="split-buttons" style="margin-top:12px"><button class="btn ghost" onclick="openSupplierForm('${s.id}')">Sửa</button><button class="btn danger" onclick="deleteSupplier('${s.id}')">Xóa</button></div>`)}

  function stockReceiptModal(m){ensure();const suppliers=(db.suppliers||[]).filter(s=>s.active!==false),supplierId=m.supplierId||'',items=m.items||[];return sheet('Phiếu nhập hàng',`<div class="form-row"><div class="field"><label>Nhà cung cấp</label><select id="sr_supplier_id" onchange="state.modal.supplierId=this.value"><option value="">— Chưa chọn —</option>${suppliers.map(s=>`<option value="${s.id}" ${String(s.id)===String(supplierId)?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Ngày nhập</label><input type="datetime-local" value="${new Date(m.date||new Date()).toISOString().slice(0,16)}" onchange="state.modal.date=new Date(this.value).toISOString()"></div></div><div class="field"><label>Quét / nhập barcode</label><div class="searchrow" style="margin:0"><input id="sr_code" placeholder="Barcode / SKU" onkeydown="if(event.key==='Enter'){addStockByCode();this.value=''}"><button class="btn accent" onclick="openScanner('stockContinuous',null,true)">📷 Quét liên tục</button></div></div><div class="inventory-receive-list">${items.map(it=>{const p=product(it.productId),count=it.imeis?.length||0,buy=Number(it.buyPrice??p?.cost)||0;return `<div class="inventory-receive-row"><div><b>${esc(p?.name||'')}</b><small>${esc(p?.sku||'')} • tồn ${p?.stock||0}${p?.imeiEnabled?' • IMEI/Serial':''}</small>${p?.imeiEnabled?`<button class="btn ${count===it.qty?'success':'ghost'} small" onclick="openStockImeis(${p.id})">IMEI ${count}/${it.qty}</button>`:''}</div><div class="field compact"><label>Giá nhập</label><input type="number" min="0" value="${buy}" onchange="setReceiptBuyPrice(${p.id},this.value)"></div><div class="qty"><button onclick="changeStockQty(${p.id},-1)">−</button><b>${it.qty}</b><button onclick="changeStockQty(${p.id},1)">＋</button></div><b class="right">${money(buy*(Number(it.qty)||0))}</b></div>`}).join('')||'<div class="empty">Chưa có sản phẩm. Quét barcode hoặc SKU để thêm hàng.</div>'}</div><div class="field"><label>Ghi chú</label><textarea id="sr_note" rows="2" oninput="state.modal.note=this.value">${esc(m.note||'')}</textarea></div><div class="row-between inventory-receive-total"><span>Tổng giá trị nhập</span><b>${money(items.reduce((a,it)=>a+(Number(it.qty)||0)*(Number(it.buyPrice??product(it.productId)?.cost)||0),0))}</b></div><button class="btn success block" onclick="finishStockReceipt()">HOÀN TẤT NHẬP HÀNG</button>`)}
  window.setReceiptBuyPrice=(id,v)=>{const it=state.modal?.items?.find(x=>x.productId===id);if(it)it.buyPrice=Math.max(0,Number(v)||0);render()};

  window.finishStockReceipt=()=>{ensure();const m=state.modal;if(!m||m.type!=='stockReceipt')return baseFinishStockReceipt?.();if(!m.items?.length)return toast('Chưa có sản phẩm');for(const it of m.items){const p=product(it.productId);if(!p)return toast('Có sản phẩm không còn tồn tại');it.buyPrice=Math.max(0,Number(it.buyPrice??p.cost)||0);if(p.imeiEnabled&&(it.imeis||[]).length!==Number(it.qty))return toast(`Nhập đủ IMEI cho ${p.name}`);for(const iid of it.imeis||[]){const val=typeof iid==='string'?iid:imeiObj(iid)?.value;if(!val)continue;if((db.imeis||[]).some(x=>x.value===val))return toast(`IMEI ${val} đã tồn tại`)}}
    const s=supplier(m.supplierId);const r={id:Date.now(),code:docCode('NH',db.stockReceipts),date:m.date||new Date().toISOString(),supplierId:s?.id||null,supplier:s?.name||'',note:m.note||'',status:'Đã nhập kho',cancelledAt:null,cancelReason:'',items:clone(m.items)};
    r.items.forEach((it,idx)=>{const p=product(it.productId),oldStock=Number(p.stock)||0,oldCost=Number(p.cost)||0,qty=Math.max(0,Number(it.qty)||0),buyPrice=Math.max(0,Number(it.buyPrice)||0),newStock=oldStock+qty,newCost=newStock>0?Math.round((oldStock*oldCost+qty*buyPrice)/newStock):buyPrice;p.stock=newStock;p.cost=newCost;it.oldCost=oldCost;it.newCost=newCost;addMovement(p.id,qty,'RECEIVE',r.code,`Nhập hàng${s?` • ${s.name}`:''}`);const h={id:Date.now()+idx+Math.random(),date:r.date,productId:p.id,supplierId:s?.id||null,supplierName:s?.name||'',receiptId:r.id,receiptCode:r.code,qty,buyPrice,oldCost,newCost};db.costHistory.unshift(h);p.costHistory.unshift(h.id);(it.imeis||[]).forEach((raw,j)=>{const value=typeof raw==='string'?raw:imeiObj(raw)?.value;if(!value)return;db.imeis.unshift({id:Date.now()+idx*100+j+Math.random(),productId:p.id,value,status:'Trong kho',stockReceiptId:r.id,customerId:null,invoiceId:null,receivedDate:r.date,soldDate:null,warrantyStart:null,warrantyEnd:null})})});db.stockReceipts.unshift(r);addActivity(`Nhập hàng ${r.code}${s?` • ${s.name}`:''}`);saveDB();state.modal=null;state.screen='stock';render();toast('Đã nhập kho và cập nhật giá vốn bình quân')};

  function adjustmentFormModal(m){const d=m.draft,available=m.available||[];return sheet('Phiếu điều chỉnh kho',`<div class="field"><label>Lý do</label><input id="adj_reason" value="${esc(d.reason||'')}"></div><div class="form-row"><div class="field"><label>Sản phẩm</label><select id="adj_product"><option value="">— Chọn sản phẩm —</option>${available.map(p=>`<option value="${p.id}">${esc(p.name)} • tồn ${p.stock}</option>`).join('')}</select></div><div class="field"><label>Chênh lệch (+/-)</label><input id="adj_delta" type="number" value="0"></div></div><button class="btn ghost block" onclick="addAdjustmentLine()">＋ Thêm dòng</button><div class="inventory-adjust-list">${d.items.map((it,i)=>{const p=product(it.productId),after=(Number(p?.stock)||0)+(Number(it.delta)||0);return `<div><span><b>${esc(p?.name||'')}</b><small>Tồn ${p?.stock||0} → ${after}</small></span><span><b class="${it.delta<0?'danger-text':'success-text'}">${it.delta>0?'+':''}${it.delta}</b><button class="btn ghost small" onclick="removeAdjustmentLine(${i})">×</button></span></div>`}).join('')||'<div class="empty">Chưa có dòng điều chỉnh.</div>'}</div><div class="field"><label>Ghi chú</label><textarea id="adj_note" rows="2">${esc(d.note||'')}</textarea></div><button class="btn primary block" onclick="saveAdjustment()">LƯU & CẬP NHẬT TỒN</button>`)}
  function adjustmentDetailModal(m){const a=m.a;return sheet(a.code,`<div class="inventory-supplier-kpis"><div><span>Ngày</span><b>${fmtDate(a.date)}</b></div><div><span>Số dòng</span><b>${(a.items||[]).length}</b></div><div><span>Trạng thái</span><b>${esc(a.status||'Hoàn thành')}</b></div></div><div class="card"><b>${esc(a.reason||'Điều chỉnh kho')}</b><div class="small muted">${esc(a.note||'')}</div></div><div class="inventory-adjust-list">${(a.items||[]).map(it=>{const p=product(it.productId);return `<div><span><b>${esc(p?.name||'')}</b><small>${it.before} → ${it.after}</small></span><b class="${it.delta<0?'danger-text':'success-text'}">${it.delta>0?'+':''}${it.delta}</b></div>`}).join('')}</div>${a.status!=='Đã hủy'?`<button class="btn danger block" style="margin-top:12px" onclick="cancelAdjustment(${a.id})">HỦY PHIẾU & ĐẢO TỒN</button>`:''}`)}

  window.exportProductsExcel=()=>{ensure();if(!window.XLSX)return toast('Chưa tải được thư viện Excel. Hãy kiểm tra mạng và thử lại.');const products=(db.products||[]).map(p=>({'SKU':p.sku||'','Barcode':p.barcode||'','Tên sản phẩm':p.name||'','Tên ngắn':p.short||'','Từ khóa':p.keywords||'','Giá vốn':Number(p.cost)||0,'Giá bán':Number(p.price)||0,'Tồn kho':Number(p.stock)||0,'Tồn tối thiểu':Number(p.minStock)||0,'Quản lý IMEI':p.imeiEnabled?'Có':'Không','Bảo hành tháng':Number(p.warranty)||0}));const suppliers=(db.suppliers||[]).map(s=>({'Mã NCC':s.code||'','Tên nhà cung cấp':s.name||'','SĐT':s.phone||'','Email':s.email||'','Địa chỉ':s.address||'','MST':s.taxCode||'','Ghi chú':s.note||'','Hoạt động':s.active===false?'Không':'Có'}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(products),'SanPham');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(suppliers),'NhaCungCap');XLSX.writeFile(wb,`KPOS-Hang-Hoa-${new Date().toISOString().slice(0,10)}.xlsx`)};
  window.importProductsExcel=()=>{if(!window.XLSX)return toast('Chưa tải được thư viện Excel. Hãy kiểm tra mạng và thử lại.');const inp=document.createElement('input');inp.type='file';inp.accept='.xlsx,.xls,.csv';inp.onchange=()=>{const f=inp.files?.[0];if(!f)return;const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});if(!rows.length)return toast('File không có dữ liệu');state.modal={type:'excelImport',rows,fileName:f.name};render()}catch(err){console.error(err);toast('Không đọc được file Excel')}};r.readAsArrayBuffer(f)};inp.click()};
  const pick=(row,names)=>{for(const n of names)if(row[n]!==undefined&&row[n]!==null&&String(row[n]).trim()!=='')return row[n];return ''};
  window.applyExcelImport=()=>{const rows=state.modal?.rows||[];if(!rows.length)return;let created=0,updated=0,stockChanged=0,imeiIgnored=0;const adj={id:Date.now(),code:docCode('DC',db.adjustmentReceipts),date:new Date().toISOString(),status:'Hoàn thành',reason:'Điều chỉnh tồn từ Excel',note:`Import ${state.modal.fileName||''}`,items:[]};for(const row of rows){const name=String(pick(row,['Tên sản phẩm','Ten san pham','Name','Product'])||'').trim(),sku=String(pick(row,['SKU','Mã SKU','Ma SKU'])||'').trim(),barcode=String(pick(row,['Barcode','Mã vạch','Ma vach'])||'').trim();if(!name&&!sku&&!barcode)continue;let p=(db.products||[]).find(x=>(sku&&String(x.sku)===sku)||(barcode&&String(x.barcode)===barcode));const isNew=!p;if(!p){p={id:Date.now()+Math.random(),name:name||sku||barcode,short:'',keywords:'',sku:sku||`SP${String(Date.now()).slice(-6)}`,barcode,cost:0,price:0,stock:0,minStock:0,imeiEnabled:false,warranty:0,images:[],costHistory:[]};db.products.unshift(p);created++}else updated++;p.name=name||p.name;p.short=String(pick(row,['Tên ngắn','Ten ngan','Short'])||p.short||'');p.keywords=String(pick(row,['Từ khóa','Tu khoa','Keywords'])||p.keywords||'');if(sku)p.sku=sku;if(barcode)p.barcode=barcode;const cost=Number(pick(row,['Giá vốn','Gia von','Cost']));if(Number.isFinite(cost)&&cost>=0)p.cost=cost;const price=Number(pick(row,['Giá bán','Gia ban','Price']));if(Number.isFinite(price)&&price>=0)p.price=price;const min=Number(pick(row,['Tồn tối thiểu','Ton toi thieu','MinStock']));if(Number.isFinite(min)&&min>=0)p.minStock=min;const warranty=Number(pick(row,['Bảo hành tháng','Bao hanh thang','Warranty']));if(Number.isFinite(warranty)&&warranty>=0)p.warranty=warranty;const imeiTxt=String(pick(row,['Quản lý IMEI','Quan ly IMEI','IMEI'])||'').toLowerCase();if(imeiTxt)p.imeiEnabled=['có','co','yes','true','1','x'].includes(imeiTxt);const importedStock=Number(pick(row,['Tồn kho','Ton kho','Stock']));if(Number.isFinite(importedStock)&&importedStock>=0){if(p.imeiEnabled){p.stock=availableImeis(p.id).length;imeiIgnored++}else{const before=Number(p.stock)||0,after=importedStock,delta=after-before;if(delta!==0){p.stock=after;adj.items.push({productId:p.id,before,after,delta});addMovement(p.id,delta,'EXCEL_IMPORT',adj.code,'Điều chỉnh tồn từ Excel');stockChanged++}}}if(isNew&&p.stock>0&&!adj.items.some(x=>x.productId===p.id)){addMovement(p.id,p.stock,'OPENING','EXCEL','Tồn khởi tạo từ Excel')}}if(adj.items.length)db.adjustmentReceipts.unshift(adj);saveDB();state.modal=null;render();toast(`Excel: tạo ${created}, cập nhật ${updated}, đổi tồn ${stockChanged}${imeiIgnored?`, bỏ qua tồn ${imeiIgnored} hàng IMEI`:''}`)};

  function excelImportModal(m){const sample=m.rows.slice(0,8);return sheet('Nhập hàng hóa từ Excel',`<div class="notice"><b>${esc(m.fileName||'')}</b><br>${m.rows.length} dòng dữ liệu. Hệ thống ghép theo SKU hoặc Barcode; nếu chưa có sẽ tạo sản phẩm mới.</div><div class="inventory-excel-preview">${sample.map(r=>`<div><b>${esc(String(pick(r,['Tên sản phẩm','Ten san pham','Name','Product'])||''))}</b><span>${esc(String(pick(r,['SKU','Mã SKU','Ma SKU'])||''))} • ${esc(String(pick(r,['Barcode','Mã vạch','Ma vach'])||''))}</span></div>`).join('')}</div><div class="notice warning">Tồn kho từ Excel chỉ tự áp dụng cho hàng không quản lý IMEI. Hàng IMEI giữ tồn theo danh sách IMEI thực tế.</div><div class="split-buttons"><button class="btn ghost" onclick="closeModal()">Hủy</button><button class="btn primary" onclick="applyExcelImport()">XÁC NHẬN IMPORT</button></div>`)}

  function extraModal(){const m=state.modal;if(!m)return null;if(m.type==='supplierForm')return supplierFormModal(m);if(m.type==='supplierDetail')return supplierDetailModal(m);if(m.type==='stockReceipt')return stockReceiptModal(m);if(m.type==='adjustmentForm')return adjustmentFormModal(m);if(m.type==='adjustmentDetail')return adjustmentDetailModal(m);if(m.type==='excelImport')return excelImportModal(m);return null}
  window.modalView=modalView=function(){const x=extraModal();return x!==null?x:baseModalView()};

  function customScreen(){if(state.screen==='suppliers')return suppliersView();if(state.screen==='stocktake')return stocktakeView();if(state.screen==='adjustments')return adjustmentsView();return null}
  window.render=render=function(){ensure();const html=customScreen();if(html!==null){app.innerHTML=html+(state.modal?modalView():'');setTimeout(injectQuickLinks,0);return}baseRender();setTimeout(injectQuickLinks,0)};

  // Ensure new stock receipt starts with fields needed by this pack.
  const baseOpenStockReceipt=window.openStockReceipt;
  window.openStockReceipt=()=>{state.modal={type:'stockReceipt',items:[],supplierId:'',note:'',date:new Date().toISOString()};render()};
})();
