/* KPOS Operations Pro - CRM pipeline + staff permissions */
(function(){
  const desktopMQ=window.matchMedia('(min-width: 980px)');
  const isDesktop=()=>desktopMQ.matches;
  const baseRender=window.render;
  const baseNav=window.nav;
  const baseModalView=window.modalView;
  const baseCrmDashboard=window.crmDashboard;
  const baseCrmReportsView=window.crmReportsView;
  const baseGo=window.go;
  const CRM_STATUSES=[['Khách mới','Khách mới'],['Chưa liên hệ','Chưa liên hệ'],['Đã liên hệ','Đã liên hệ'],['Đang tư vấn','Đang tư vấn'],['Khách quan tâm','Khách quan tâm'],['Chờ khách phản hồi','Chờ phản hồi'],['Hẹn gọi lại','Hẹn gọi lại'],['Hẹn gặp/demo','Hẹn gặp / demo'],['Đang báo giá','Đang báo giá'],['Đang cân nhắc','Đang cân nhắc'],['Đã mua hàng','Đã mua / Đã chốt'],['Không mua','Không mua'],['Mất khách','Mất khách']];
  window.KPOS_CRM_STATUSES=CRM_STATUSES;

  function crmPipeline(){return `<div class="biz-pipeline">${CRM_STATUSES.map(([v,l])=>{const rows=db.customers.filter(c=>(c.status||'Khách mới')===v);return `<section class="biz-pipe-col"><header><b>${esc(l)}</b><span>${rows.length}</span></header><div>${rows.slice(0,30).map(c=>`<button class="biz-crm-card" onclick="openDesktopCrmDetail(${c.id})"><b>${esc(c.name)}</b><small>${esc(c.phone||'')}</small><div>${esc(c.need||'Chưa ghi nhu cầu')}</div>${c.nextCareAt?`<em class="${new Date(c.nextCareAt)<new Date()?'late':''}">${fmtDateTime(c.nextCareAt)}</em>`:''}</button>`).join('')||'<div class="biz-pipe-empty">Trống</div>'}</div></section>`}).join('')}</div>`}
  window.crmDashboard=crmDashboard=function(){
    if(!isDesktop())return baseCrmDashboard();const today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1),dueToday=db.customers.filter(c=>c.nextCareAt&&new Date(c.nextCareAt)>=today&&new Date(c.nextCareAt)<tomorrow).length,overdue=db.customers.filter(c=>c.nextCareAt&&new Date(c.nextCareAt)<new Date()&&!['Đã mua hàng','Không mua','Mất khách'].includes(c.status)).length;
    return `${topbar('CRM Pipeline','13 trạng thái • nhu cầu • lịch care • theo dõi chốt khách')}<div class="content biz-crm-pipeline-page">${typeof crmTabs==='function'?crmTabs('crmDashboard'):''}<div class="biz-crm-summary"><div><b>${db.customers.length}</b><span>Tổng khách</span></div><div><b>${dueToday}</b><span>Care hôm nay</span></div><div class="danger"><b>${overdue}</b><span>Quá hạn</span></div><div><b>${db.customers.filter(c=>c.status==='Đã mua hàng').length}</b><span>Đã chốt</span></div><button class="btn primary" onclick="openCrmCustomerForm()">＋ Thêm khách CRM</button></div>${crmPipeline()}</div>${nav()}`;
  };
  window.crmReportsView=crmReportsView=function(){if(!isDesktop())return baseCrmReportsView();return `${topbar('Báo cáo CRM','Pipeline đầy đủ theo trạng thái')}<div class="content">${typeof crmTabs==='function'?crmTabs('crmReports'):''}<div class="biz-status-report">${CRM_STATUSES.map(([v,l])=>`<div class="pro-kpi"><div><div class="pro-kpi-label">${esc(l)}</div><div class="pro-kpi-value">${db.customers.filter(c=>c.status===v).length}</div></div></div>`).join('')}</div></div>${nav()}`};

  window.saveCrmCustomer=()=>{const m=state.modal;if(!m||m.type!=='crmForm')return;const c=m.c;c.name=$('#crmf_name')?.value.trim()||'';c.phone=$('#crmf_phone')?.value.trim()||'';c.status=$('#crmf_status')?.value||'Khách mới';c.need=$('#crmf_need')?.value.trim()||'';c.budget=$('#crmf_budget')?.value.trim()||'';c.careChannel=$('#crmf_channel')?.value||'Gọi điện';c.note=$('#crmf_note')?.value.trim()||'';c.source=$('#crmf_source')?.value.trim()||c.source||'';const next=$('#crmf_next')?.value;c.nextCareAt=next?new Date(next).toISOString():'';if(!c.name)return toast('Nhập tên khách hàng');if(m.editing){const idx=db.customers.findIndex(x=>x.id===c.id);if(idx>=0)db.customers[idx]=c}else{c.id=Date.now();c.total=c.total||0;c.debt=c.debt||0;c.careHistory=c.careHistory||[];db.customers.unshift(c)}addActivity(`CRM • ${c.name} • ${c.status}`);saveDB();state.modal=null;state.screen='crmCustomers';render()};
  function crmFormModal(m){const c=m.c;return sheet(m.editing?'Sửa khách CRM':'Thêm khách CRM',`<div class="form-row"><div class="field"><label>Họ tên *</label><input id="crmf_name" value="${esc(c.name||'')}"></div><div class="field"><label>Số điện thoại</label><input id="crmf_phone" value="${esc(c.phone||'')}"></div></div><div class="form-row"><div class="field"><label>Tình trạng khách</label><select id="crmf_status">${CRM_STATUSES.map(([v,l])=>`<option value="${esc(v)}" ${v===(c.status||'Khách mới')?'selected':''}>${esc(l)}</option>`).join('')}</select></div><div class="field"><label>Nguồn khách</label><input id="crmf_source" value="${esc(c.source||'')}" placeholder="Facebook, Zalo, giới thiệu..."></div></div><div class="field"><label>Khách cần gì?</label><textarea id="crmf_need" rows="3" placeholder="VD: Máy POS + máy in bill + phần mềm">${esc(c.need||'')}</textarea></div><div class="field"><label>Ngân sách dự kiến</label><input id="crmf_budget" value="${esc(c.budget||'')}" placeholder="VD: 7–8 triệu"></div><div class="form-row"><div class="field"><label>Care tiếp theo</label><input id="crmf_next" type="datetime-local" value="${c.nextCareAt?new Date(c.nextCareAt).toISOString().slice(0,16):''}"></div><div class="field"><label>Kênh care</label><select id="crmf_channel">${['Gọi điện','Zalo','Facebook','Email','Gặp trực tiếp'].map(x=>`<option ${x===c.careChannel?'selected':''}>${x}</option>`).join('')}</select></div></div><div class="field"><label>Ghi chú</label><textarea id="crmf_note" rows="3">${esc(c.note||'')}</textarea></div><button class="btn primary block" onclick="saveCrmCustomer()">LƯU KHÁCH CRM</button>`)}

  const PERMISSIONS=[['pos','Bán hàng / POS'],['products','Sản phẩm'],['inventory','Kho & IMEI'],['customers','Khách hàng'],['crm','CRM'],['warranty','Bảo hành'],['debts','Công nợ'],['reports','Báo cáo'],['settings','Cài đặt']];
  const SCREEN_PERMISSION={pos:'pos',products:'products',stock:'inventory',inventory:'inventory',imei:'inventory',customers:'customers',crmDashboard:'crm',crmCustomers:'crm',crmToday:'crm',crmOverdue:'crm',crmReports:'crm',warranty:'warranty',debts:'debts',payments:'debts',reports:'reports',prints:'settings',settings:'settings',staff:'settings'};
  function cloud(){return window.KPOS_CLOUD||{}}
  function can(feature){const c=cloud();if(!c.configured)return true;if(c.role==='owner'||c.role==='manager')return true;if(!c.user)return false;return !!(c.memberPermissions||{})[feature]}
  window.kposCan=can;
  window.go=s=>{const f=SCREEN_PERMISSION[s];if(f&&!can(f))return toast('Tài khoản của bạn chưa được cấp quyền vào chức năng này');baseGo(s)};
  async function loadMyPermissions(){const c=cloud();if(!c.client||!c.user||!c.workspaceId||c._permissionLoading||c._permissionsLoaded)return;c._permissionLoading=true;try{const {data,error}=await c.client.from('kpos_members').select('permissions').eq('workspace_id',c.workspaceId).eq('user_id',c.user.id).single();if(!error){c.memberPermissions=data?.permissions||{};c._permissionsLoaded=true}}catch(e){}finally{c._permissionLoading=false}}
  function roleLabel(r){return r==='owner'?'Chủ cửa hàng':r==='manager'?'Quản lý':'Nhân viên'}
  function staffView(){const c=cloud();return `${topbar('Nhân viên & phân quyền','Tài khoản dùng chung workspace KPOS')}<div class="content biz-staff-page"><div class="biz-staff-head"><div><h2>Nhân viên</h2><div class="small muted">Thêm tài khoản đã đăng ký KPOS và cấp quyền theo module.</div></div>${['owner','manager'].includes(c.role)?'<button class="btn primary" onclick="openStaffForm()">＋ Thêm nhân viên</button>':''}</div><div id="bizStaffList"><div class="empty">Đang tải danh sách nhân viên…</div></div></div>${nav()}`}
  window.loadStaffMembers=async()=>{const c=cloud(),el=$('#bizStaffList');if(!el)return;if(!c.client||!c.workspaceId){el.innerHTML='<div class="empty">Chưa kết nối Supabase.</div>';return}const {data,error}=await c.client.rpc('kpos_list_members',{p_workspace:c.workspaceId});if(error){el.innerHTML=`<div class="notice">${esc(error.message||'Không tải được nhân viên')}</div>`;return}c.staffMembers=data||[];el.innerHTML=`<div class="biz-staff-table"><div class="biz-staff-row head"><div>Tài khoản</div><div>Vai trò</div><div>Quyền</div><div></div></div>${(data||[]).map(m=>`<div class="biz-staff-row"><div><b>${esc(m.display_name||m.email||'')}</b><div class="small muted">${esc(m.email||'')}</div></div><div><span class="badge ${m.role==='owner'?'orange':''}">${roleLabel(m.role)}</span></div><div class="biz-perm-tags">${m.role==='owner'?'<span>Tất cả quyền</span>':PERMISSIONS.filter(([k])=>m.permissions?.[k]).map(([,l])=>`<span>${esc(l)}</span>`).join('')||'<span>Chưa cấp quyền</span>'}</div><div class="right">${m.role!=='owner'&&['owner','manager'].includes(c.role)?`<button class="btn ghost small" onclick="openStaffForm('${m.user_id}')">Sửa</button> <button class="btn danger small" onclick="removeStaff('${m.user_id}')">Xóa</button>`:''}</div></div>`).join('')}</div>`};
  window.openStaffForm=userId=>{const c=cloud(),existing=(c.staffMembers||[]).find(x=>x.user_id===userId);state.modal={type:'staffForm',member:existing||{email:'',role:'staff',permissions:{pos:true,products:true,inventory:true,customers:true,crm:true,warranty:true,debts:true,reports:false,settings:false}},editing:!!existing};render()};
  function staffFormModal(m){const x=m.member;return sheet(m.editing?'Sửa nhân viên':'Thêm nhân viên',`<div class="field"><label>Email tài khoản KPOS</label><input id="staff_email" type="email" value="${esc(x.email||'')}" ${m.editing?'disabled':''} placeholder="nhanvien@email.com"></div><div class="field"><label>Vai trò</label><select id="staff_role"><option value="staff" ${x.role==='staff'?'selected':''}>Nhân viên</option><option value="manager" ${x.role==='manager'?'selected':''}>Quản lý</option></select></div><div class="section-title">Quyền sử dụng</div><div class="biz-perm-grid">${PERMISSIONS.map(([k,l])=>`<label><input id="perm_${k}" type="checkbox" ${x.permissions?.[k]?'checked':''}> ${esc(l)}</label>`).join('')}</div><div class="notice" style="margin:12px 0">Email phải đã tạo tài khoản KPOS trước. Chủ cửa hàng có toàn quyền.</div><button class="btn primary block" onclick="saveStaffMember()">LƯU NHÂN VIÊN</button>`)}
  function readPermissions(){return Object.fromEntries(PERMISSIONS.map(([k])=>[k,!!$(`#perm_${k}`)?.checked]))}
  window.saveStaffMember=async()=>{const c=cloud(),m=state.modal;if(!c.client||!c.workspaceId)return toast('Chưa kết nối Supabase');const role=$('#staff_role')?.value||'staff',permissions=readPermissions();try{let r;if(m.editing)r=await c.client.rpc('kpos_update_member',{p_workspace:c.workspaceId,p_user:m.member.user_id,p_role:role,p_permissions:permissions});else r=await c.client.rpc('kpos_add_member_by_email',{p_workspace:c.workspaceId,p_email:$('#staff_email')?.value.trim(),p_role:role,p_permissions:permissions});if(r.error)throw r.error;state.modal=null;render();setTimeout(loadStaffMembers,100);toast('Đã lưu nhân viên')}catch(e){toast(e.message||'Không lưu được nhân viên')}};
  window.removeStaff=async userId=>{const c=cloud();if(!confirm('Xóa nhân viên này khỏi workspace KPOS?'))return;const {error}=await c.client.rpc('kpos_remove_member',{p_workspace:c.workspaceId,p_user:userId});if(error)return toast(error.message);render();setTimeout(loadStaffMembers,100);toast('Đã xóa nhân viên')};

  window.nav=nav=function(){let html=baseNav();if(!isDesktop())return html;const c=cloud();if(!['owner','manager'].includes(c.role))return html;const item=`<button class="desktop-nav-btn ${state.screen==='staff'?'active':''}" onclick="go('staff')"><span class="ico">👥</span><span>Nhân viên & quyền</span></button>`;return html.replace('<div class="desktop-nav-group">Hệ thống</div>',`<div class="desktop-nav-group">Nhân sự</div>${item}<div class="desktop-nav-group">Hệ thống</div>`)};
  window.modalView=modalView=function(){if(state.modal?.type==='crmForm')return crmFormModal(state.modal);if(state.modal?.type==='staffForm')return staffFormModal(state.modal);return baseModalView()};
  window.render=render=function(){loadMyPermissions();if(state.screen==='staff')app.innerHTML=staffView()+modalView();else baseRender();setTimeout(()=>{if(state.screen==='staff')loadStaffMembers()},0)};
})();
