/* KPOS Print Agent LAN/WiFi - local bridge to ESC/POS network printers */
(function(){
  const baseRender=window.render;
  const baseFinishCheckout=window.finishCheckout;
  const AGENT_DEFAULT='http://127.0.0.1:17654';

  function cfg(){
    db.appSettings=db.appSettings||{};
    db.appSettings.printAgent={enabled:false,agentUrl:AGENT_DEFAULT,host:'192.168.1.100',port:9100,paper:'K80',copies:1,autoPrint:false,cut:true,...(db.appSettings.printAgent||{})};
    return db.appSettings.printAgent;
  }
  cfg();
  const cleanUrl=v=>String(v||AGENT_DEFAULT).trim().replace(/\/$/,'');
  async function callAgent(path,payload=null,ms=4500){
    const c=cfg(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);
    try{
      const options={method:payload?'POST':'GET',mode:'cors',cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json'}};
      if(payload)options.body=JSON.stringify(payload);
      const r=await fetch(`${cleanUrl(c.agentUrl)}${path}`,options);
      const data=await r.json().catch(()=>({ok:false,error:`HTTP ${r.status}`}));
      if(!r.ok||data.ok===false)throw new Error(data.error||`HTTP ${r.status}`);
      return data;
    }finally{clearTimeout(timer)}
  }
  window.KPOS_PRINT_AGENT={call:callAgent,config:cfg};
  window.savePrintAgentSettings=()=>{const c=cfg();c.enabled=!!$('#pa_enabled')?.checked;c.agentUrl=cleanUrl($('#pa_agent')?.value||AGENT_DEFAULT);c.host=$('#pa_host')?.value.trim()||'';c.port=Math.max(1,Math.min(65535,Number($('#pa_port')?.value)||9100));c.paper=$('#pa_paper')?.value||'K80';c.copies=Math.max(1,Math.min(5,Number($('#pa_copies')?.value)||1));c.autoPrint=!!$('#pa_auto')?.checked;c.cut=!!$('#pa_cut')?.checked;saveDB();toast('Đã lưu cấu hình máy in LAN/WiFi');render()};
  function setAgentStatus(text,ok=null){const el=$('#pa_status');if(!el)return;el.textContent=text;el.className=`pa-status ${ok===true?'ok':ok===false?'bad':''}`}
  window.testKposPrintAgent=async()=>{setAgentStatus('Đang kiểm tra Print Agent…');try{const r=await callAgent('/health',null,2500);setAgentStatus(`✓ Print Agent ${r.version||''} đang chạy`,true)}catch(e){setAgentStatus(`Không kết nối được Print Agent: ${e.message}`,false)}};
  window.testKposPrinterConnection=async()=>{const c=cfg();setAgentStatus(`Đang kết nối ${c.host}:${c.port}…`);try{const r=await callAgent('/test-connection',{host:c.host,port:c.port,timeoutMs:2500},4000);setAgentStatus(`✓ Đã kết nối máy in ${r.host||c.host}:${r.port||c.port}`,true)}catch(e){setAgentStatus(`Không kết nối được máy in: ${e.message}`,false)}};
  function moneyText(v){try{return money(Number(v)||0)}catch(e){return `${Number(v)||0}đ`}}
  function invoiceLines(inv){const p=db.storeProfile||{},c=inv.customerId?customer(inv.customerId):null,lines=[],add=(text,opt={})=>lines.push({text:String(text??''),...opt});add(p.name||p.short||'KPOS',{align:'center',bold:true,size:28});if(p.address)add(p.address,{align:'center',size:18});if(p.phone)add(`Hotline: ${p.phone}`,{align:'center',size:18});add('HÓA ĐƠN BÁN HÀNG',{align:'center',bold:true,size:25,spaceTop:8});add(`Mã: ${inv.code||''}`,{bold:true});add(`Ngày: ${typeof fmtDateTime==='function'?fmtDateTime(inv.date):new Date(inv.date).toLocaleString('vi-VN')}`);add(`Khách: ${c?.name||'Khách lẻ'}${c?.phone?` • ${c.phone}`:''}`);add('----------------------------------------------',{size:17});(inv.items||[]).forEach((it,idx)=>{const pr=product(it.productId),price=Number(it.price??pr?.price)||0,qty=Number(it.qty)||0;add(`${idx+1}. ${pr?.name||'Sản phẩm'}`,{bold:true});add(`   ${qty} x ${moneyText(price)} = ${moneyText(price*qty)}`);if((it.imeis||[]).length)add(`   IMEI: ${(it.imeis||[]).map(id=>imeiObj(id)?.value||id).join(', ')}`,{size:17});if(it.note)add(`   Ghi chú: ${it.note}`,{size:17})});add('----------------------------------------------',{size:17});add(`Tạm tính: ${moneyText(inv.subtotal??inv.total)}`,{align:'right'});if(Number(inv.discount)>0)add(`Giảm giá: -${moneyText(inv.discount)}`,{align:'right'});if(Number(inv.voucherDiscount)>0)add(`Voucher: -${moneyText(inv.voucherDiscount)}`,{align:'right'});if(Number(inv.pointsDiscount)>0)add(`Điểm: -${moneyText(inv.pointsDiscount)}`,{align:'right'});if(Number(inv.surcharge)>0)add(`${inv.surchargeName||'Phụ thu'}: +${moneyText(inv.surcharge)}`,{align:'right'});if(Number(inv.shipping)>0)add(`Giao hàng: +${moneyText(inv.shipping)}`,{align:'right'});add(`TỔNG CỘNG: ${moneyText(inv.total)}`,{align:'right',bold:true,size:26,spaceTop:5});if(inv.paymentMethod)add(`Thanh toán: ${inv.paymentMethod}`,{size:18});if(Number(inv.debt)>0)add(`CÔNG NỢ: ${moneyText(inv.debt)}`,{bold:true,size:20});if(inv.note)add(`Ghi chú HĐ: ${inv.note}`,{size:17});add('----------------------------------------------',{size:17});add(p.footer||'Cảm ơn Quý khách!',{align:'center',size:18,spaceTop:7});return lines}
  function wrapCanvasText(ctx,text,maxWidth){const words=String(text||'').split(/\s+/),rows=[];let row='';for(const word of words){const test=row?`${row} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&row){rows.push(row);row=word}else row=test}if(row)rows.push(row);return rows.length?rows:['']}
  window.buildKposK80Image=async inv=>{const width=576,margin=20,lines=invoiceLines(inv),probe=document.createElement('canvas').getContext('2d');let height=28;const measured=[];for(const line of lines){const size=line.size||19;probe.font=`${line.bold?'700':'400'} ${size}px Arial, sans-serif`;const rows=wrapCanvasText(probe,line.text,width-margin*2),lh=Math.ceil(size*1.38),block=rows.length*lh+(line.spaceTop||0)+4;height+=block;measured.push({...line,size,rows,lh})}height+=34;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=Math.max(240,height);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';ctx.textBaseline='top';let y=18;for(const line of measured){y+=line.spaceTop||0;ctx.font=`${line.bold?'700':'400'} ${line.size}px Arial, sans-serif`;for(const row of line.rows){let x=margin;if(line.align==='center')x=width/2;else if(line.align==='right')x=width-margin;ctx.textAlign=line.align||'left';ctx.fillText(row,x,y);y+=line.lh}y+=4}return canvas.toDataURL('image/png')};
  window.directPrintInvoice=async(inv,opts={})=>{const c=cfg();if(!c.enabled)throw new Error('Chưa bật Print Agent trong Cài đặt');if(!c.host)throw new Error('Chưa nhập IP máy in');const image=await buildKposK80Image(inv),base64=image.split(',')[1];return callAgent('/print-image',{host:c.host,port:c.port,imageBase64:base64,copies:opts.copies||c.copies||1,cut:c.cut!==false},15000)};
  window.printCurrentInvoiceLan=async id=>{const inv=(db.invoices||[]).find(x=>String(x.id)===String(id));if(!inv)return toast('Không tìm thấy hóa đơn');try{toast('Đang gửi hóa đơn tới máy in…');await directPrintInvoice(inv);toast('✓ Đã gửi lệnh in LAN/WiFi')}catch(e){toast(`In LAN/WiFi lỗi: ${e.message}`)}};
  window.testKposPrinterPrint=async()=>{const c=cfg(),sample={id:'test',code:'TEST-KPOS',date:new Date().toISOString(),customerId:null,subtotal:123000,discount:3000,total:120000,debt:0,paymentMethod:'Tiền mặt 120.000đ',items:[{productId:null,qty:1,price:120000,note:'Bản in thử KPOS',imeis:[]}],note:'Kết nối LAN/WiFi thành công'};try{setAgentStatus('Đang gửi bản in thử…');await directPrintInvoice(sample,{copies:1});setAgentStatus(`✓ Đã gửi bản in thử tới ${c.host}:${c.port}`,true)}catch(e){setAgentStatus(`In thử thất bại: ${e.message}`,false)}};
  window.finishCheckoutAndPrint=()=>{window.__KPOS_FORCE_PRINT=true;finishCheckout()};
  if(baseFinishCheckout){window.finishCheckout=()=>{const before=(db.invoices||[])[0]?.id,force=!!window.__KPOS_FORCE_PRINT;window.__KPOS_FORCE_PRINT=false;const result=baseFinishCheckout();const inv=(db.invoices||[])[0],created=inv&&String(inv.id)!==String(before);if(created&&(force||cfg().autoPrint)&&cfg().enabled){setTimeout(()=>directPrintInvoice(inv).then(()=>toast('✓ Đã gửi in LAN/WiFi')).catch(e=>toast(`Không in tự động được: ${e.message}`)),120)}return result}}
  function card(){const c=cfg();return `<div id="kpos-print-agent-card" class="pa-card"><div class="pa-head"><div><b>🖨️ KPOS Print Agent LAN/WiFi</b><small>In K80 trực tiếp qua IP máy in • không phí hàng tháng</small></div><label class="pa-enable"><input id="pa_enabled" type="checkbox" ${c.enabled?'checked':''}> Bật</label></div><div class="pa-grid"><label>Địa chỉ Print Agent<input id="pa_agent" value="${esc(c.agentUrl||AGENT_DEFAULT)}" placeholder="${AGENT_DEFAULT}"></label><label>IP máy in<input id="pa_host" value="${esc(c.host||'')}" placeholder="192.168.1.100"></label><label>Port<input id="pa_port" type="number" value="${Number(c.port)||9100}"></label><label>Khổ giấy<select id="pa_paper"><option value="K80" ${c.paper==='K80'?'selected':''}>K80 / 80mm</option></select></label><label>Số bản<input id="pa_copies" type="number" min="1" max="5" value="${Number(c.copies)||1}"></label></div><div class="pa-switches"><label><input id="pa_auto" type="checkbox" ${c.autoPrint?'checked':''}> Tự in sau khi thanh toán</label><label><input id="pa_cut" type="checkbox" ${c.cut!==false?'checked':''}> Cắt giấy sau khi in</label></div><div id="pa_status" class="pa-status">Print Agent chạy trên máy tính tại ${esc(c.agentUrl||AGENT_DEFAULT)}</div><div class="pa-actions"><button class="btn primary" onclick="savePrintAgentSettings()">LƯU CẤU HÌNH</button><button class="btn ghost" onclick="testKposPrintAgent()">1. TEST AGENT</button><button class="btn ghost" onclick="testKposPrinterConnection()">2. TEST MÁY IN</button><button class="btn ghost" onclick="testKposPrinterPrint()">3. IN THỬ</button></div><div class="small muted" style="margin-top:10px">Máy tính và máy in phải cùng mạng LAN/WiFi. Máy in cần hỗ trợ RAW/ESC-POS qua TCP, thường dùng port 9100.</div></div>`}
  function injectSettings(){if(state.screen!=='settings'||document.querySelector('#kpos-print-agent-card'))return;const target=document.querySelector('#sv2-print .sv2-card-body')||document.querySelector('.content');if(target)target.insertAdjacentHTML('beforeend',card())}
  function injectCheckoutButton(){if(state.modal?.type!=='posV3Checkout'||document.querySelector('#pa-checkout-print'))return;const btn=[...document.querySelectorAll('.pos3-checkout-modal button.btn.success.block')][0];if(!btn)return;const c=cfg(),b=document.createElement('button');b.id='pa-checkout-print';b.className='btn primary block pa-checkout-print';b.textContent='THANH TOÁN & IN LAN/WIFI';b.onclick=()=>finishCheckoutAndPrint();btn.insertAdjacentElement('afterend',b);if(c.autoPrint&&c.enabled)btn.textContent='HOÀN TẤT (TỰ IN ĐANG BẬT)'}
  function injectSuccessButton(){const m=state.modal;if(m?.type!=='success'||!m.invoice||document.querySelector('#pa-success-print'))return;const sheet=document.querySelector('.sheet,.pos3-quick-modal,.pos3-checkout-modal');if(!sheet)return;const b=document.createElement('button');b.id='pa-success-print';b.className='btn ghost block';b.style.marginTop='8px';b.textContent='🖨️ IN LẠI QUA LAN/WIFI';b.onclick=()=>printCurrentInvoiceLan(m.invoice.id);sheet.appendChild(b)}
  window.render=render=function(){const r=baseRender();setTimeout(()=>{injectSettings();injectCheckoutButton();injectSuccessButton()},0);return r};
})();