/* KPOS Returns Pack - returns/exchanges/refunds/stock/IMEI/debt */
(function(){
  const desktopMQ=window.matchMedia('(min-width:980px)');
  const isDesktop=()=>desktopMQ.matches;
  const baseModalView=window.modalView;
  const baseRender=window.render;
  const baseNav=window.nav;
  function ensure(){if(!Array.isArray(db.returns))db.returns=[];(db.invoices||[]).forEach(i=>{if(!Number.isFinite(Number(i.returnedAmount)))i.returnedAmount=0})}
  ensure();
  function list(invId){return db.returns.filter(r=>r.invoiceId===invId&&r.status!=='Đã hủy')}
  function qty(invId,idx){return list(invId).reduce((s,r)=>s+(r.items||[]).filter(x=>x.sourceIndex===idx).reduce((a,b)=>a+(Number(b.qty)||0),0),0)}
  function imeisReturned(invId){const out=new Set();list(invId).forEach(r=>(r.items||[]).forEach(x=>(x.imeis||[]).forEach(id=>out.add(String(id)))));return out}
  function fullyReturned(inv){return (inv.items||[]).every((it,idx)=>qty(inv.id,idx)>=(Number(it.qty)||0))}
  function suggested(m){const inv=m.inv,subtotal=Number(inv.subtotal)||((inv.items||[]).reduce((s,it)=>s+(Number(it.qty)||0)*(Number(it.price)||0),0)),net=Math.max(0,subtotal-(Number(inv.discount)||0)-(Number(inv.voucherDiscount)||0)-(Number(inv.pointsDiscount)||0)),factor=subtotal?Math.min(1,net/subtotal):1,gross=m.items.reduce((s,x)=>s+(Number(x.qty)||0)*(Number(x.price)||0),0);return Math.round(gross*factor)}
  function refreshAmount(){const m=state.modal;if(m?.type!=='returnForm')return;const v=suggested(m);if(!m.customAmount)m.refundAmount=v;const i=$('#ret_amount');if(i&&!m.customAmount)i.value=v;const l=$('#ret_suggested');if(l)l.textContent=money(v)}

  window.openReturnForm=invId=>{ensure();const inv=invoice(invId);if(!inv)return toast('Không tìm thấy hóa đơn');if(inv.status==='Đã hủy')return toast('Hóa đơn đã hủy không thể trả hàng');if(fullyReturned(inv))return toast('Hóa đơn đã trả hết hàng');const used=imeisReturned(inv.id),items=(inv.items||[]).map((it,idx)=>({sourceIndex:idx,productId:it.productId,price:Number(it.price)||0,maxQty:Math.max(0,(Number(it.qty)||0)-qty(inv.id,idx)),qty:0,imeis:[],availableImeis:(it.imeis||[]).filter(id=>!used.has(String(id)))}));state.modal={type:'returnForm',inv,items,mode:'return',customAmount:false,refundAmount:0};render()};
  window.setReturnQty=(idx,val)=>{const x=state.modal?.items?.[idx];if(!x)return;x.qty=Math.max(0,Math.min(x.maxQty,Number(val)||0));refreshAmount()};
  window.toggleReturnImei=(idx,id,checked)=>{const x=state.modal?.items?.[idx];if(!x)return;x.imeis=x.imeis||[];if(checked&&!x.imeis.some(v=>String(v)===String(id)))x.imeis.push(id);if(!checked)x.imeis=x.imeis.filter(v=>String(v)!==String(id));x.qty=x.imeis.length;refreshAmount()};
  window.setReturnMode=v=>{if(state.modal?.type==='returnForm'){state.modal.mode=v;render()}};
  window.setReturnCustomAmount=()=>{if(state.modal?.type==='returnForm'){state.modal.customAmount=true;state.modal.refundAmount=Math.max(0,Number($('#ret_amount')?.value)||0)}};

  window.saveReturn=()=>{ensure();const m=state.modal;if(m?.type!=='returnForm')return;const inv=m.inv,c=customer(inv.customerId),selected=m.items.filter(x=>(Number(x.qty)||0)>0);if(!selected.length)return toast('Chọn ít nhất 1 sản phẩm cần trả');for(const x of selected){const p=product(x.productId);if(x.qty>x.maxQty)return toast(`Số lượng trả vượt quá ${p?.name||'sản phẩm'}`);if(p?.imeiEnabled){if((x.imeis||[]).length!==x.qty)return toast(`Chọn đúng ${x.qty} IMEI cho ${p.name}`);for(const iid of x.imeis){const im=imeiObj(iid);if(!im)return toast('Không tìm thấy IMEI');if(im.status==='Bảo hành')return toast(`IMEI ${im.value} đang bảo hành`)}}}
    const maxRefund=Math.max(0,(Number(inv.total)||0)-(Number(inv.returnedAmount)||0)),amount=Math.max(0,Math.min(maxRefund,Number($('#ret_amount')?.value)||suggested(m)));if(!amount)return toast('Số tiền hoàn phải lớn hơn 0');const mode=$('#ret_mode')?.value||m.mode||'return',method=$('#ret_method')?.value||'Tiền mặt',reason=$('#ret_reason')?.value.trim()||'',note=$('#ret_note')?.value.trim()||'',now=new Date().toISOString(),r={id:Date.now(),code:code('TH',db.returns),date:now,invoiceId:inv.id,invoiceCode:inv.code,customerId:inv.customerId||null,type:mode,refundMethod:method,reason,note,amount,debtOffset:0,refundPaid:0,status:'Hoàn thành',items:selected.map(x=>({sourceIndex:x.sourceIndex,productId:x.productId,qty:x.qty,price:x.price,imeis:[...(x.imeis||[])]}))};
    let returnedCost=0;r.items.forEach(x=>{const p=product(x.productId);if(!p)return;p.stock=(Number(p.stock)||0)+x.qty;returnedCost+=(Number(p.cost)||0)*x.qty;addMovement(p.id,x.qty,'RETURN',r.code,`Trả hàng từ ${inv.code}`);(x.imeis||[]).forEach(iid=>{const im=imeiObj(iid);if(im){im.status='Trong kho';im.customerId=null;im.invoiceId=null;im.soldDate=null;im.warrantyStart=null;im.warrantyEnd=null}})});
    const debtOffset=Math.min(amount,Number(inv.debt)||0,c?Number(c.debt)||0:0),refund=Math.max(0,amount-debtOffset);r.debtOffset=debtOffset;r.refundPaid=refund;inv.debt=Math.max(0,(Number(inv.debt)||0)-debtOffset);if(c)c.debt=Math.max(0,(Number(c.debt)||0)-debtOffset);if(refund>0&&method!=='Không hoàn tiền')db.payments.unshift({id:Date.now()+9,code:code('HT',db.payments),date:now,customerId:inv.customerId||null,invoiceId:inv.id,amount:-refund,method,status:'Hoàn tiền',note:`Hoàn tiền ${r.code} • ${inv.code}`});inv.returnedAmount=(Number(inv.returnedAmount)||0)+amount;inv.paid=Math.max(0,(Number(inv.paid)||Math.max(0,(Number(inv.total)||0)-(Number(inv.debt)||0)))-refund);if(c)c.total=Math.max(0,(Number(c.total)||0)-amount);r.profitImpact=amount-returnedCost;db.returns.unshift(r);inv.status=fullyReturned(inv)?'Đã trả hàng':'Trả một phần';addActivity(`${r.code} • ${mode==='exchange'?'Đổi hàng':'Trả hàng'} • ${inv.code} • ${money(amount)}`);saveDB();if(mode==='exchange'){state.activeCustomer=c||null;state.modal=null;state.screen='pos';render();toast('Đã hoàn kho. Chọn sản phẩm mới để tạo đơn đổi hàng.');return}state.modal={type:'invoiceDetail',inv};render();toast('Đã xử lý trả hàng và hoàn kho')};

  function returnModal(m){const inv=m.inv,c=customer(inv.customerId),s=suggested(m);if(!m.customAmount)m.refundAmount=s;return sheet(`Trả / đổi hàng • ${inv.code}`,`<div class="notice"><b>${esc(c?.name||'Khách lẻ')}</b> • Hóa đơn ${money(inv.total)}${inv.debt?` • Còn nợ ${money(inv.debt)}`:''}</div><div class="field" style="margin-top:12px"><label>Hình thức</label><select id="ret_mode" onchange="setReturnMode(this.value)"><option value="return" ${m.mode==='return'?'selected':''}>Trả hàng / hoàn tiền</option><option value="exchange" ${m.mode==='exchange'?'selected':''}>Đổi hàng / tạo đơn mới</option></select></div><div class="return-pack-list">${m.items.map((x,idx)=>{const p=product(x.productId);if(!x.maxQty)return '';return `<div class="return-pack-item"><div><b>${esc(p?.name||'Sản phẩm')}</b><div class="small muted">Có thể trả ${x.maxQty} • ${money(x.price)}</div>${p?.imeiEnabled?`<div class="return-imeis">${x.availableImeis.map(id=>{const im=imeiObj(id);return `<label><input type="checkbox" ${x.imeis.some(v=>String(v)===String(id))?'checked':''} onchange="toggleReturnImei(${idx},${JSON.stringify(id)},this.checked)"> <span class="mono">${esc(im?.value||String(id))}</span></label>`}).join('')}</div>`:''}</div>${p?.imeiEnabled?`<b>${x.qty}/${x.maxQty}</b>`:`<input class="return-qty" type="number" min="0" max="${x.maxQty}" value="${x.qty}" oninput="setReturnQty(${idx},this.value)">`}</div>`}).join('')}</div><div class="form-row" style="margin-top:12px"><div class="field"><label>Số tiền hoàn</label><input id="ret_amount" type="number" value="${m.refundAmount}" oninput="setReturnCustomAmount()"><div class="small muted">Gợi ý: <b id="ret_suggested">${money(s)}</b></div></div><div class="field"><label>Phương thức hoàn</label><select id="ret_method"><option>Tiền mặt</option><option>Chuyển khoản</option><option>Thẻ/POS</option><option>Không hoàn tiền</option></select></div></div><div class="form-row"><div class="field"><label>Lý do</label><input id="ret_reason" placeholder="Đổi mẫu, lỗi sản phẩm..."></div><div class="field"><label>Ghi chú</label><input id="ret_note" placeholder="Ghi chú nội bộ"></div></div><div class="notice" style="margin-bottom:12px">Nếu hóa đơn còn công nợ, hệ thống sẽ <b>trừ công nợ trước</b>; phần còn lại mới hoàn theo phương thức đã chọn.</div><button class="btn danger block" onclick="saveReturn()">XÁC NHẬN ${m.mode==='exchange'?'ĐỔI HÀNG':'TRẢ HÀNG'}</button>`)}

  function invoiceModal(inv){const c=customer(inv.customerId),rs=list(inv.id),done=fullyReturned(inv);return sheet(inv.code,`<div class="info-grid"><div class="info-box"><div class="k">TỔNG TIỀN</div><div class="v">${money(inv.total)}</div></div><div class="info-box"><div class="k">ĐÃ TRẢ / ĐỔI</div><div class="v ${inv.returnedAmount?'danger-text':''}">${money(inv.returnedAmount||0)}</div></div><div class="info-box"><div class="k">CÒN NỢ</div><div class="v ${inv.debt?'danger-text':''}">${money(inv.debt||0)}</div></div><div class="info-box"><div class="k">KHÁCH</div><div class="v">${esc(c?.name||'Khách lẻ')}</div></div></div><div class="section-title">Sản phẩm</div><div class="list">${(inv.items||[]).map((it,idx)=>{const p=product(it.productId),rq=qty(inv.id,idx);return `<div class="item"><div class="item-main"><b>${esc(p?.name||'')}</b><div class="small muted">${it.qty} × ${money(it.price)}${rq?` • Đã trả ${rq}`:''}</div>${it.imeis?.length?`<div class="taglist" style="margin-top:6px">${it.imeis.map(id=>`<span class="imei-tag mono">${esc(imeiObj(id)?.value||'')}</span>`).join('')}</div>`:''}</div><b>${money((it.qty||0)*(it.price||0))}</b></div>`}).join('')}</div>${rs.length?`<div class="section-title">Lịch sử trả / đổi</div><div class="return-history">${rs.map(r=>`<div><span><b>${esc(r.code)}</b><small>${fmtDateTime(r.date)} • ${r.type==='exchange'?'Đổi hàng':'Trả hàng'}</small></span><b>${money(r.amount)}</b></div>`).join('')}</div>`:''}<div class="small muted" style="margin-top:12px">${fmtDateTime(inv.date)} • ${esc(inv.status||'')}</div><div class="return-actions"><button class="btn ghost" onclick="previewTemplate('sale_k80','invoice',${inv.id})">K80</button><button class="btn ghost" onclick="previewTemplate('sale_a4','invoice',${inv.id})">A4</button><button class="btn danger" onclick="openReturnForm(${inv.id})" ${done||inv.status==='Đã hủy'?'disabled':''}>↩ Trả / đổi hàng</button></div>`)}

  function returnsView(){ensure();return `${topbar('Trả / đổi hàng','Hoàn tiền • hoàn tồn kho • IMEI/Serial • công nợ')}<div class="content"><div class="return-table"><div class="return-row head"><div>Phiếu</div><div>Hóa đơn / khách</div><div>Hình thức</div><div>Số tiền</div></div>${db.returns.map(r=>{const c=customer(r.customerId);return `<button class="return-row" onclick="openInvoiceDetail(${r.invoiceId})"><div><b>${esc(r.code)}</b><small>${fmtDateTime(r.date)}</small></div><div><b>${esc(r.invoiceCode||'')}</b><small>${esc(c?.name||'Khách lẻ')}</small></div><div><span class="badge ${r.type==='exchange'?'orange':'green'}">${r.type==='exchange'?'Đổi hàng':'Trả hàng'}</span><small>${esc(r.refundMethod||'')}</small></div><div class="right"><b>${money(r.amount)}</b><small>${r.debtOffset?`Trừ nợ ${money(r.debtOffset)}`:''}</small></div></button>`}).join('')||'<div class="empty">Chưa có phiếu trả / đổi hàng.</div>'}</div></div>${nav()}`}

  window.nav=nav=function(){let html=baseNav();if(!isDesktop())return html;const item=`<button class="desktop-nav-btn ${state.screen==='returns'?'active':''}" onclick="go('returns')"><span class="ico">↩</span><span>Trả / đổi hàng</span></button>`;return html.replace('<div class="desktop-nav-group">Hàng hóa & kho</div>',item+'<div class="desktop-nav-group">Hàng hóa & kho</div>')};
  window.modalView=modalView=function(){if(state.modal?.type==='returnForm')return returnModal(state.modal);if(state.modal?.type==='invoiceDetail')return invoiceModal(state.modal.inv);return baseModalView()};
  window.render=render=function(){ensure();if(state.screen==='returns')app.innerHTML=returnsView()+modalView();else baseRender()};
})();