/* KPOS Desktop Table Pack - normalize remaining management screens */
(function(){
  const desktopMQ=window.matchMedia('(min-width:980px)');
  const isDesktop=()=>desktopMQ.matches;
  const baseImeiCards=window.imeiCards;
  const baseWarrantyCards=window.warrantyCards;
  const basePaymentsView=window.paymentsView;
  const baseStockView=window.stockView;
  const baseInventoryView=window.inventoryView;
  const baseDebtsView=window.debtsView;

  function wideTable(head,rows,empty='Chưa có dữ liệu'){return `<div class="foundation-wide-table"><div class="foundation-wide-row head">${head.map(x=>`<div>${x}</div>`).join('')}</div>${rows||`<div class="empty">${empty}</div>`}</div>`}

  window.imeiCards=imeiCards=function(list){if(!isDesktop())return baseImeiCards(list);return list.map(i=>{const p=product(i.productId),c=customer(i.customerId);return `<button class="item foundation-row" onclick="openImeiDetail(${i.id})"><div><b class="mono">${esc(i.value)}</b><small>${i.warrantyEnd?`BH đến ${fmtDate(i.warrantyEnd)}`:'Chưa có hạn BH'}</small></div><div><b>${esc(p?.name||'Không rõ sản phẩm')}</b><small>${esc(c?.name||'Chưa bán')}${c?.phone?` • ${esc(c.phone)}`:''}</small></div><div class="right"><span class="badge ${i.status==='Trong kho'?'green':i.status==='Bảo hành'?'orange':''}">${esc(i.status||'')}</span><small>${i.soldDate?fmtDate(i.soldDate):'Trong kho'}</small></div></button>`}).join('')||'<div class="empty">Chưa có IMEI / Serial</div>'};

  window.warrantyCards=warrantyCards=function(list){if(!isDesktop())return baseWarrantyCards(list);return list.map(w=>`<button class="item foundation-row" onclick="openWarrantyDetail(${w.id})"><div><b>${esc(w.code)}</b><small class="mono">${esc(w.imei||'')}</small></div><div><b>${esc(w.customerName||'Khách lẻ')}</b><small>${esc(w.productName||'')} • ${esc(w.phone||'')}</small></div><div class="right"><span class="badge ${w.status==='Đã trả khách'||w.status==='Hoàn thành'?'green':'orange'}">${esc(w.status||'')}</span><small>${w.promisedAt?`Hẹn ${fmtDate(w.promisedAt)}`:fmtDate(w.date)}</small></div></button>`).join('')||'<div class="empty">Chưa có phiếu bảo hành</div>'};

  window.paymentsView=paymentsView=function(){if(!isDesktop())return basePaymentsView();const rows=(db.payments||[]).map(p=>{const c=customer(p.customerId),inv=invoice(p.invoiceId),negative=Number(p.amount)<0;return `<div class="foundation-wide-row ${p.status==='Đã hủy'?'is-cancelled':''}"><div><b>${esc(p.code)}</b><small>${fmtDateTime(p.date)}</small></div><div><b>${esc(c?.name||'Khách lẻ')}</b><small>${esc(p.method||'')} ${inv?`• ${esc(inv.code)}`:''}</small></div><div><span class="badge ${p.status==='Đã hủy'?'red':negative?'orange':'green'}">${esc(p.status||'Hoàn thành')}</span></div><div class="right"><b class="${negative?'danger-text':''}">${money(p.amount)}</b><small>${esc(p.note||'')}</small></div></div>`}).join('');return `${topbar('Thu tiền','Thanh toán • thu công nợ • hoàn tiền')}<div class="content">${wideTable(['Phiếu / thời gian','Khách hàng / phương thức','Trạng thái','Số tiền'],rows,'Chưa có giao dịch')}</div>${nav()}`};

  window.stockView=stockView=function(){if(!isDesktop())return baseStockView();const rows=(db.stockReceipts||[]).map(r=>`<div class="foundation-wide-row"><div><b>${esc(r.code)}</b><small>${fmtDateTime(r.date)}</small></div><div><b>${esc(r.supplier||'Chưa ghi NCC')}</b><small>${esc(r.note||'')}</small></div><div><b>${(r.items||[]).reduce((a,b)=>a+(Number(b.qty)||0),0)} SP</b><small>${(r.items||[]).filter(x=>product(x.productId)?.imeiEnabled).reduce((a,b)=>a+(b.imeis?.length||0),0)} IMEI</small></div><div class="right"><span class="badge green">Đã nhập kho</span></div></div>`).join('');return `${topbar('Nhập hàng','Phiếu nhập • barcode • IMEI/Serial')}<div class="content"><div class="foundation-page-actions"><button class="btn primary" onclick="openStockReceipt()">＋ Tạo phiếu nhập</button><button class="btn ghost" onclick="openScanner('stockContinuous',null,true)">📷 Quét liên tục</button></div>${wideTable(['Phiếu nhập','Nhà cung cấp / ghi chú','Số lượng','Trạng thái'],rows,'Chưa có phiếu nhập')}</div>${nav()}`};

  window.inventoryView=inventoryView=function(){if(!isDesktop())return baseInventoryView();const rows=(db.inventoryMovements||[]).map(m=>{const p=product(m.productId);return `<div class="foundation-wide-row"><div><b>${esc(p?.name||'')}</b><small>${esc(p?.sku||'')}</small></div><div><b>${esc(m.code||'')}</b><small>${fmtDateTime(m.date)} • ${esc(m.note||'')}</small></div><div><span class="badge ${Number(m.qty)>=0?'green':'orange'}">${Number(m.qty)>=0?'+':''}${m.qty}</span></div><div class="right"><b>Tồn ${m.balance}</b><small>${esc(m.type||'')}</small></div></div>`}).join('');return `${topbar('Lịch sử kho','Nhập • bán • trả hàng • hủy • điều chỉnh')}<div class="content">${wideTable(['Sản phẩm','Chứng từ / thời gian','Biến động','Tồn sau'],rows,'Chưa có biến động kho')}</div>${nav()}`};

  window.debtsView=debtsView=function(){if(!isDesktop())return baseDebtsView();const list=(db.customers||[]).filter(c=>(Number(c.debt)||0)>0).sort((a,b)=>b.debt-a.debt),total=list.reduce((a,b)=>a+(Number(b.debt)||0),0),rows=list.map(c=>`<div class="foundation-wide-row"><div><b>${esc(c.name)}</b><small>${esc(c.phone||'')}</small></div><div><b>${money(c.total||0)}</b><small>${esc(c.status||'')}</small></div><div><span class="badge red">Đang nợ</span></div><div class="right"><b class="danger-text">${money(c.debt)}</b><button class="btn success small" onclick="openDebtPayment(${c.id})">Thu tiền</button></div></div>`).join('');return `${topbar('Công nợ','Theo dõi và thu tiền khách hàng')}<div class="content"><div class="foundation-debt-summary">${stat('Khách đang nợ',list.length)}${stat('Tổng công nợ',money(total))}</div>${wideTable(['Khách hàng','Doanh số / CRM','Trạng thái','Còn phải thu'],rows,'Không có công nợ')}</div>${nav()}`};
})();
